apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: csi-snapshot-controller-pdb
  namespace: ${CONTROLPLANE_NAMESPACE}
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: csi-snapshot-controller
  unhealthyEvictionPolicy: AlwaysAllow
